import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import * as activityLogRepository from "../repositories/local.log.repository"
import * as eventRepository from "../repositories/local.event.repository"
import ActivityLogItems from "./_component/activity-log";
import EventLists from "./_component/event-list";
import { cookies } from "next/headers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const cookiesStore = await cookies();
  const correlation_id = cookiesStore.get("correlation")?.value;
  const activityLogs = await activityLogRepository.getActivityLogsByCorrelationId(correlation_id as string) || [];
  const events = await eventRepository.getAllLocalEvent() || [];
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col items-center justify-center min-h-screen gap-6">
        {children}
        <div className="flex flex-col items-center justify-center text-2xl font-bold mb-4 pb-4 border-b-2 border-gray-300">        
          <ActivityLogItems logs={activityLogs} />
        </div>

        <div className="flex flex-col items-center justify-center text-2xl font-bold mb-4 pb-4 border-b-2 border-gray-300">        
            <EventLists event={events} />
        </div>
      </body>
    </html>
  );
}
